### ISSUE TITLE
fix gem dependencies

### ISSUE THREAD

**Issue by kajatiger** [rails-girls-summer-of-code/summer-of-code#389] opened 2017-07-25 07:47 UTC
After running `gem install bundler` it got messy. First the Ruby version was wrong and a lower one had to be installed, then nokogiri couldn't be properly installed by the bundler. I had to install xcode select and then install the right nokogirir version manually. And then the jeykyll had to be installed manually as well and it didn't start the server without running `bundle exec`.

**Comment by alicetragedy** [comment] 2017-07-27 11:14
hey @kajatiger, thanks for opening this issue. This is very helpful information, we'll look into it!

**Comment by MrAaronOlsen** [comment] 2017-09-19 16:57
@alicetragedy I can confirm that Ruby 2.4.2 works. I also removed versions from jekyll and github-pages to let them update to the latest, and so far everything seems to load fine. It looks like the last time jekyll was updated was about a year ago. Jekyll is at 3.5.2 and github pages are at 161. I'm not sure if it's worth testing through to make sure everything else still works fine with updated gems.

Maybe it would be worth updating the readme to mention Rvm, and note that you need to install bundler again with new Ruby versions. This may prevent what @kajatiger experienced? In my experience Ruby versioning does mess with nokogiri. The solution has been to bundle update to reset the Gemfile.lock after adding a version to Rvm.

Also, Ruby versioning can be held in the Gemfile rather than a separate ruby-version file. It looks like there's questions on a PR if that file, or even versioning Ruby at all, is necessary. I'd think versioning Ruby is good practice until you can confirm it doesn't break anything. Let me know what direction you think it would be good to go in or if you already have some ideas.

**Comment by alicetragedy** [comment] 2018-01-25 17:43
Hi @MrAaronOlsen I realise now that I never got back to you on this. Is this something you're interested in helping with? It would be much appreciated! 
A few answers to your questions/comments:
- I agree that updating the readme to include information about rvm (or rbenv) and the note about bundler makes sense. 
- versioning Ruby is definitely a good idea, particularly with so many different people involved in contributing to this repo. I _think_ that the separate `.ruby-version` file only is useful for people using a ruby versioning tool (aka RVM or rbenv). To avoid people having to install that when making contributions, maybe the better way to go would be to switch to having that info in the Gemfile and/or to keeping both (but then we have to make sure that the information in both files in synced). I personally prefer the ruby version file separate, but I don't want this to be a hurdle for non-Rubyists. What do you think?
- Last but not least, +1 on “we should probably update jekyll and the ruby version more regularly” 😅 

please let me know if any of this is something you'd be interested in contributing to — either way, thanks again to you and @kajatiger for creating the bug report and looking into it. 🙌

**Comment by wiseemily88** [comment] 2018-02-26 22:10
Hi there!  @alicetragedy I’m a first-time contributor and was hoping to help out with this issue. I noticed that a PR has not been submitted for this issue. Submitting a PR with a potential fix. Thanks!

**Comment by alicetragedy** [comment] 2018-03-07 11:33
Hi @wiseemily88 — thank you so much for contributing and submitting your PR, and congratulations on your first contribution to our `summer-of-code` repo  🎉 🙌
I've assigned the PR to myself and will be looking at it very soon. Sorry for the delay!

**Comment by alicetragedy** [comment] 2018-11-18 18:38
hej @kajatiger — I will be adding the information about adding `bundle exec` to the jekyll command to start the server to the readme, but other than that, I believe that @wiseemily88's PR https://github.com/rails-girls-summer-of-code/summer-of-code/pull/483 should have helped. Thank you for reporting this! 🙌

**Comment by alicetragedy** [comment] 2019-03-26 15:27
contribution guidelines were updated accordingly in https://github.com/rails-girls-summer-of-code/summer-of-code/commit/2676dc5784c81f18df44a7e030232dfa66d031f0, closing this issue!

**Closed as completed by alicetragedy** 2019-03-26 15:27 UTC
Labels: bug, help wanted
