### ISSUE TITLE
404 error page after click on the logo on donation page

### ISSUE THREAD

**Issue by 1000miles** [rails-girls-summer-of-code/summer-of-code#203] opened 2016-03-23 19:57 UTC
Dear all,

not sure if this is already noticed but I guess the redirect link of the rgsoc logo on the donation page (`http://railsgirlsberlin.github.io/summer-of-code`) needs to be updated? 

![rgsoc_broken_link_2016-03-23_0200](https://cloud.githubusercontent.com/assets/4077916/13998525/f8636114-f137-11e5-8749-a30b6f3812e1.png)

Also the README.file?

![00001034](https://cloud.githubusercontent.com/assets/4077916/13998811/78f3eda2-f139-11e5-8bcd-18c058778499.png)

**Comment by alicetragedy** [comment] 2016-03-23 20:01
thanks for this! I will take a look today or tomorrow <3

**Comment by 1000miles** [comment] 2016-03-23 20:04
wow! that was a quick reply. thank you. <3

**Comment by alicetragedy** [comment] 2016-03-23 20:18
@1000miles of course, you're also welcome to create a pull request, if you want to change it yourself :sparkles:

**Comment by 1000miles** [comment] 2016-03-24 08:50
@alicetragedy okay, i'll do it. is it enough, if i do it tomorrow? :) thanks for updating the readme-file already. :+1:

**Comment by alicetragedy** [comment] 2016-03-24 08:53
@1000miles absolutely. the thing is, I can't reproduce it locally, and I really don't understand where that link actually comes from. please ping me though if you need help! I will be around.

**Comment by 1000miles** [comment] 2016-03-25 11:21
@alicetragedy I tried to reproduce it and it is still there as you can see from the screenshot. At the bottom you see the link to `railsgirlsberlin.github.io/summer-of-code` when I hover over the logo. :)

<img width="1280" alt="screen shot 2016-03-25 at 11 56 33 2" src="https://cloud.githubusercontent.com/assets/4077916/14043092/e13749c0-f280-11e5-9ab9-c11a552cdd19.png">

When I try to access the path `/donations/checkout/ directly I only see this:

<img width="1280" alt="screen shot 2016-03-25 at 12 00 28 2" src="https://cloud.githubusercontent.com/assets/4077916/14043138/51666488-f281-11e5-80b1-4fd83cfe7b33.png">

In the code I see this:

```
$(document).ready(function() {
  $(function() {
    if(location.hostname == 'localhost') {
      $('#stripe-form').attr('action', 'http://localhost:3000/donations/checkout');
    }
  });
```

It looks as if there is a redirect to another host and the form points to an old template? I can not find the template for this page in the project. Is it hosted anywhere else?

**Comment by alicetragedy** [comment] 2016-04-01 15:36
hey @1000miles, thanks for looking into it (and sorry I didn't reply sooner). It seems like part of the campaign stuff is handled in another repo, which is why it was not possible to find the link to fix :see_no_evil: 
I've found it now and made changes here: https://github.com/rails-girls-summer-of-code/rgsoc-campaign/commit/b0f9f505d5e926849cfa2f3f78c918bbcd29a8cc
that should hopefully fix it. thank you for your help!

**Comment by 1000miles** [comment] 2016-04-04 16:11
@alicetragedy Sorry, I was abroad and just came back yesterday. Thanks for looking into this. 

I just tested it again (also in incognito mode with Firefox and Chrome) but it's still there. 

<img width="1274" alt="00000066" src="https://cloud.githubusercontent.com/assets/4077916/14248123/1e6084de-fa73-11e5-95e9-b3f0b6ab6fc5.png">

**Comment by alicetragedy** [comment] 2016-04-06 09:14
@svenfuchs do you have any idea how I can fix this? 
I've pushed a commit which I hoped would fix it (and assumed it gets deployed automatically) but it looks as though this issue is still there. it's not a big deal, but it's annoying. Is there any way you can help? :) (I'm also not very familiar with the campaign page / donation setup)

**Comment by svenfuchs** [comment] 2016-04-06 09:27
@1000miles thanks for reporting! @alicetragedy, i believe that's these: https://github.com/rails-girls-summer-of-code/rgsoc-campaign/blob/b0f9f505d5e926849cfa2f3f78c918bbcd29a8cc/app/views/layouts/application.html.slim#L17-L21

**Comment by alicetragedy** [comment] 2016-04-06 10:59
@1000miles I've deployed, so I believe this should be fixed :) feel free to close if that's the case!

**Comment by 1000miles** [comment] 2016-04-06 11:49
@alicetragedy Looks good to me, thank you! :) What was it finally? Because the last merge was not deployed yet?

**Comment by alicetragedy** [comment] 2016-04-06 11:51
@1000miles yes, my commit was not deployed. quite a stupid mistake :p 
but yeah, the issue was in another repo (so that's also quite confusing for bug reporting). thank you for helping us out on this one, I guess we can close it then :tada:

**Closed as completed by alicetragedy** 2016-04-06 11:51 UTC
