### ISSUE TITLE
timeline stars flicker when hovering on main page sections

### ISSUE THREAD

**Issue by alicetragedy** [rails-girls-summer-of-code/summer-of-code#215] opened 2016-06-06 21:08 UTC
The right side ⭐ list elements of the timeline on the main index flicker (as in, disappear and then reappear) when hovering on the different landing-teasers. This seems to be triggered by a combination of the `transform` on the landing-teaser link hover and of the `display: inline-block` set on an element with `.fa` class (a font awesome default). 

Not sure what the best way to overwrite it is, but it probably shouldn't be overwritten at the top class level.

**Comment by claucece** [comment] 2016-08-15 04:41
Weird behavior. Looks like it is due to the 'transform' property. But, when the screen is resized is gone. I'll dig in it further.

**Comment by alicetragedy** [comment] 2016-08-15 10:36
great, thank you @claucece! 👍

**Comment by mkalininait** [comment] 2016-10-07 23:48
Can't reproduce anymore. Should we close it?

**Closed as completed** 2016-10-09 10:40 UTC
Labels: bug
